server.port=8888
spring.application.name=config-server

# Use "native" profile to read from local filesystem instead of git.
# For git-backed setup, use spring.cloud.config.server.git.uri
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:./../config-repo/
